#!/bin/bash -ex
if [ "$1" == "" ]; then
    echo "specify the version to merge, such as 1.383"
    exit
fi
git fetch --tags community
git checkout ich
v=$(show-pom-version pom.xml)

git checkout "$1"
mvn -B org.apache.maven.plugins:maven-release-plugin:2.0:update-versions -DdevelopmentVersion=$v
git commit -am "aligned the version number toward integration"
id=$(git show --format=format:%H HEAD | head -1)
git checkout ich
git merge $id

mvn -B org.apache.maven.plugins:maven-release-plugin:2.0:update-versions -DdevelopmentVersion=$1.1
git commit -am "next version is $1.1"

